import { FileSearch } from 'lucide-react'
import RoadmapNotice from '../../components/shared/RoadmapNotice'

export default function QuizAnalyticsAdminPage() {
  return (
    <RoadmapNotice
      title="Assessment Psychometrics &amp; Item Response Theory (IRT)"
      subtitle="Scientific evaluation of item difficulty (P-value), point-biserial discrimination, and Cronbach alpha test reliability"
      icon={FileSearch}
      phase="Phase II Psychometric Engine"
      description="In an institutional examination rollout, psychometric item analytics requires large-sample test-taker cohorts (&gt;500 completed responses per question) to mathematically calibrate item difficulty, distractor plausibility, and Item Characteristic Curves (ICC). This ensures that assessments generated by AI or NSSTA faculty meet rigorous civil service psychometric validity standards."
      prerequisites={[
        'Statistically significant response volume (minimum 200–500 submissions per question item).',
        'Item Response Theory (2PL/3PL IRT) parameter estimation engine.',
        'Official NSSTA Psychometrics Review Board sign-off workflow.',
      ]}
    />
  )
}
